import type {
  ContratoExtraido,
  ContratoListado,
  Propiedad,
  Propietario,
  Reclamo,
  ScreeningResultado,
} from './types';

export const contratosMock: ContratoListado[] = [
  {
    id: 'cnt_001',
    inquilino: 'Mariela Sosa',
    direccion: 'Gorriti 4521, 3°B',
    monto: 480000,
    moneda: 'ARS',
    estado: 'ACTIVO',
    fechaInicio: '2025-09-01',
    fechaFin: '2028-08-31',
    proximoVencimiento: '2026-05-10',
    estadoPagoActual: 'PENDIENTE',
  },
  {
    id: 'cnt_002',
    inquilino: 'Juan Pérez',
    direccion: 'Av. Cabildo 2890, 7°A',
    monto: 620000,
    moneda: 'ARS',
    estado: 'ACTIVO',
    fechaInicio: '2024-03-01',
    fechaFin: '2027-02-28',
    proximoVencimiento: '2026-05-08',
    estadoPagoActual: 'PAGADO',
  },
  {
    id: 'cnt_003',
    inquilino: 'Laura Giménez',
    direccion: 'Jorge Newbery 1820',
    monto: 510000,
    moneda: 'ARS',
    estado: 'ACTIVO',
    fechaInicio: '2025-01-15',
    fechaFin: '2028-01-14',
    proximoVencimiento: '2026-05-15',
    estadoPagoActual: 'VENCIDO',
  },
  {
    id: 'cnt_004',
    inquilino: 'Carlos Romero',
    direccion: 'Honduras 4490, PB',
    monto: 720000,
    moneda: 'ARS',
    estado: 'ACTIVO',
    fechaInicio: '2024-11-01',
    fechaFin: '2027-10-31',
    proximoVencimiento: '2026-05-05',
    estadoPagoActual: 'PAGADO',
  },
  {
    id: 'cnt_005',
    inquilino: 'Ana Pereyra',
    direccion: 'Salguero 2240, 12°D',
    monto: 850000,
    moneda: 'ARS',
    estado: 'ACTIVO',
    fechaInicio: '2025-04-01',
    fechaFin: '2028-03-31',
    proximoVencimiento: '2026-05-10',
    estadoPagoActual: 'PENDIENTE',
  },
  {
    id: 'cnt_006',
    inquilino: 'Tomás Bravo',
    direccion: 'Olleros 3920',
    monto: 1200,
    moneda: 'USD',
    estado: 'BORRADOR',
    fechaInicio: '2026-06-01',
    fechaFin: '2029-05-31',
    proximoVencimiento: '2026-06-01',
    estadoPagoActual: 'PENDIENTE',
  },
];

export const contratoExtraidoMock: ContratoExtraido = {
  inquilino: { valor: 'Mariela Sosa', confianza: 'alto' },
  cuit: { valor: '27-32567890-4', confianza: 'alto' },
  direccion: { valor: 'Gorriti 4521, 3°B', confianza: 'alto' },
  montoInicial: { valor: 480000, confianza: 'alto' },
  moneda: { valor: 'ARS', confianza: 'alto' },
  fechaInicio: { valor: '2025-09-01', confianza: 'alto' },
  fechaFin: { valor: '2028-08-31', confianza: 'alto' },
  diaPago: { valor: 5, confianza: 'medio' },
  indiceAjuste: { valor: 'ICL', confianza: 'alto' },
  frecuenciaAjusteMeses: { valor: 12, confianza: 'alto' },
  comisionInmobiliaria: { valor: 4.17, confianza: 'medio' },
  depositoGarantia: { valor: 480000, confianza: 'alto' },
  tasaPunitorioDiaria: { valor: 0.001, confianza: 'bajo' },
};

export const screeningMock: ScreeningResultado = {
  cuit: '20-31256789-0',
  nombre: 'Carlos Eduardo Méndez',
  scoreNosis: 742,
  resultadoBcra: 1,
  deudasCount: 0,
  deudasMonto: 0,
  chequesRechazados: 0,
  juiciosCount: 0,
  recomendacion: 'APTO',
  recomendacionRazon:
    'Score Nosis 742 (alto), BCRA categoría 1 (sin atrasos), sin deudas ni juicios. Cumple criterios objetivos de aptitud sin requerir garantía adicional.',
};

export const dashboardMetricsMock = {
  contratosActivos: 87,
  cobroDelMesPct: 84,
  morosos: 6,
  ingresosMes: 41850000,
};

export const operadoresMock = ['Roberto Tapia', 'Luciana Vidal', 'Sergio Almeida'] as const;

export const reclamosMock: Reclamo[] = [
  {
    id: 'rec_001',
    contratoId: 'cnt_001',
    inquilino: 'Mariela Sosa',
    direccion: 'Gorriti 4521, 3°B',
    categoria: 'PLOMERIA',
    descripcion: 'Pierde la canilla del baño desde anoche. Goteo constante.',
    urgencia: 'MEDIA',
    estado: 'ABIERTO',
    asignadoA: null,
    fotoUrl: null,
    resolucion: null,
    createdAt: '2026-05-09T14:32:00-03:00',
    resueltoAt: null,
    eventos: [
      {
        id: 'ev_001_1',
        tipo: 'CREADO',
        autor: 'Mariela Sosa',
        contenido: null,
        fecha: '2026-05-09T14:32:00-03:00',
      },
    ],
  },
  {
    id: 'rec_002',
    contratoId: 'cnt_003',
    inquilino: 'Laura Giménez',
    direccion: 'Jorge Newbery 1820',
    categoria: 'CALEFACCION',
    descripcion: 'No prende la caldera. Hace 2 días sin agua caliente.',
    urgencia: 'ALTA',
    estado: 'EN_CURSO',
    asignadoA: 'Sergio Almeida',
    fotoUrl: null,
    resolucion: null,
    createdAt: '2026-05-08T09:15:00-03:00',
    resueltoAt: null,
    eventos: [
      {
        id: 'ev_002_1',
        tipo: 'CREADO',
        autor: 'Laura Giménez',
        contenido: null,
        fecha: '2026-05-08T09:15:00-03:00',
      },
      {
        id: 'ev_002_2',
        tipo: 'ASIGNADO',
        autor: 'Roberto Tapia',
        contenido: 'Sergio Almeida',
        fecha: '2026-05-08T11:20:00-03:00',
      },
      {
        id: 'ev_002_3',
        tipo: 'MENSAJE_INMO',
        autor: 'Sergio Almeida',
        contenido: 'Hola Laura, te paso a visitar mañana entre 10 y 12 con el gasista. ¿Estás?',
        fecha: '2026-05-08T11:35:00-03:00',
      },
      {
        id: 'ev_002_4',
        tipo: 'MENSAJE_INQUILINO',
        autor: 'Laura Giménez',
        contenido: 'Sí, te espero. Gracias!',
        fecha: '2026-05-08T12:10:00-03:00',
      },
      {
        id: 'ev_002_5',
        tipo: 'EN_CURSO',
        autor: 'Sergio Almeida',
        contenido: 'Pasó el gasista, hay que cambiar termocupla. Volvemos mañana.',
        fecha: '2026-05-09T13:00:00-03:00',
      },
    ],
  },
  {
    id: 'rec_003',
    contratoId: 'cnt_004',
    inquilino: 'Carlos Romero',
    direccion: 'Honduras 4490, PB',
    categoria: 'ELECTRICIDAD',
    descripcion: 'Saltó el térmico de la cocina. Probé reset y no anda.',
    urgencia: 'EMERGENCIA',
    estado: 'ABIERTO',
    asignadoA: null,
    fotoUrl: null,
    resolucion: null,
    createdAt: '2026-05-09T18:42:00-03:00',
    resueltoAt: null,
    eventos: [
      {
        id: 'ev_003_1',
        tipo: 'CREADO',
        autor: 'Carlos Romero',
        contenido: null,
        fecha: '2026-05-09T18:42:00-03:00',
      },
    ],
  },
  {
    id: 'rec_004',
    contratoId: 'cnt_005',
    inquilino: 'Ana Pereyra',
    direccion: 'Salguero 2240, 12°D',
    categoria: 'CERRADURA',
    descripcion: 'La cerradura del balcón está dura. Dificultad para abrir.',
    urgencia: 'BAJA',
    estado: 'EN_CURSO',
    asignadoA: 'Luciana Vidal',
    fotoUrl: null,
    resolucion: null,
    createdAt: '2026-05-06T11:00:00-03:00',
    resueltoAt: null,
    eventos: [
      {
        id: 'ev_004_1',
        tipo: 'CREADO',
        autor: 'Ana Pereyra',
        contenido: null,
        fecha: '2026-05-06T11:00:00-03:00',
      },
      {
        id: 'ev_004_2',
        tipo: 'ASIGNADO',
        autor: 'Roberto Tapia',
        contenido: 'Luciana Vidal',
        fecha: '2026-05-07T09:00:00-03:00',
      },
    ],
  },
  {
    id: 'rec_005',
    contratoId: 'cnt_002',
    inquilino: 'Juan Pérez',
    direccion: 'Av. Cabildo 2890, 7°A',
    categoria: 'OTRO',
    descripcion: 'El portero eléctrico tiene interferencia.',
    urgencia: 'BAJA',
    estado: 'RESUELTO',
    asignadoA: 'Sergio Almeida',
    fotoUrl: null,
    resolucion: 'Se cambió el módulo del portero. Funciona OK.',
    createdAt: '2026-05-03T16:20:00-03:00',
    resueltoAt: '2026-05-05T10:30:00-03:00',
    eventos: [
      {
        id: 'ev_005_1',
        tipo: 'CREADO',
        autor: 'Juan Pérez',
        contenido: null,
        fecha: '2026-05-03T16:20:00-03:00',
      },
      {
        id: 'ev_005_2',
        tipo: 'ASIGNADO',
        autor: 'Roberto Tapia',
        contenido: 'Sergio Almeida',
        fecha: '2026-05-04T08:30:00-03:00',
      },
      {
        id: 'ev_005_3',
        tipo: 'RESUELTO',
        autor: 'Sergio Almeida',
        contenido: 'Se cambió el módulo del portero. Funciona OK.',
        fecha: '2026-05-05T10:30:00-03:00',
      },
    ],
  },
  {
    id: 'rec_006',
    contratoId: 'cnt_001',
    inquilino: 'Mariela Sosa',
    direccion: 'Gorriti 4521, 3°B',
    categoria: 'PLOMERIA',
    descripcion: 'Inodoro con pérdida en la base.',
    urgencia: 'MEDIA',
    estado: 'RESUELTO',
    asignadoA: 'Sergio Almeida',
    fotoUrl: null,
    resolucion: 'Cambio de empaque y silicona perimetral. Sin filtraciones.',
    createdAt: '2026-04-28T13:00:00-03:00',
    resueltoAt: '2026-04-30T17:00:00-03:00',
    eventos: [
      {
        id: 'ev_006_1',
        tipo: 'CREADO',
        autor: 'Mariela Sosa',
        contenido: null,
        fecha: '2026-04-28T13:00:00-03:00',
      },
      {
        id: 'ev_006_2',
        tipo: 'ASIGNADO',
        autor: 'Roberto Tapia',
        contenido: 'Sergio Almeida',
        fecha: '2026-04-28T15:00:00-03:00',
      },
      {
        id: 'ev_006_3',
        tipo: 'EN_CURSO',
        autor: 'Sergio Almeida',
        contenido: 'Voy mañana 10am con plomero.',
        fecha: '2026-04-29T18:00:00-03:00',
      },
      {
        id: 'ev_006_4',
        tipo: 'RESUELTO',
        autor: 'Sergio Almeida',
        contenido: 'Cambio de empaque y silicona perimetral. Sin filtraciones.',
        fecha: '2026-04-30T17:00:00-03:00',
      },
    ],
  },
];

// Propietarios usan prefijo `own_` (de "owner") para no chocar con IDs de
// propiedades (prefijo `prp_`).
export const propietariosMock: Propietario[] = [
  {
    id: 'own_001',
    nombre: 'Eduardo',
    apellido: 'Castro',
    cuit: '20-12345678-2',
    email: 'eduardo.castro@gmail.com',
    telefono: '+54 11 4789 1234',
    cbuAlias: 'castro.eduardo.cuenta',
    comisionPct: 8,
    notas: 'Pide rendición los días 10 de cada mes. Prefiere WhatsApp.',
    createdAt: '2024-08-15',
    propiedadesIds: ['prp_001'],
    totalCobradoMes: 572000,
    totalRecibirMes: 526240,
  },
  {
    id: 'own_002',
    nombre: 'Silvana',
    apellido: 'Morales',
    cuit: '27-23456789-3',
    email: 'silvanamorales@gmail.com',
    telefono: '+54 9 11 5432 6789',
    cbuAlias: 'morales.silvana',
    comisionPct: 7,
    notas: null,
    createdAt: '2023-11-02',
    propiedadesIds: ['prp_002', 'prp_004'],
    totalCobradoMes: 1340000,
    totalRecibirMes: 1246200,
  },
  {
    id: 'own_003',
    nombre: 'Federico',
    apellido: 'López Vega',
    cuit: '20-34567890-4',
    email: 'federico.lv@outlook.com',
    telefono: '+54 11 5678 9012',
    cbuAlias: null,
    comisionPct: 8,
    notas: 'Cuenta nueva — falta CBU. Reclamar en la próxima rendición.',
    createdAt: '2025-02-20',
    propiedadesIds: ['prp_003'],
    totalCobradoMes: 510000,
    totalRecibirMes: 469200,
  },
  {
    id: 'own_004',
    nombre: 'Patricia',
    apellido: 'Iglesias',
    cuit: '27-45678901-5',
    email: 'patriciaiglesias@yahoo.com.ar',
    telefono: '+54 9 351 4321 9876',
    cbuAlias: 'iglesias.patricia',
    comisionPct: 6.5,
    notas: 'Vive en Córdoba. Tiene 2 unidades funcionales en CABA.',
    createdAt: '2022-05-10',
    propiedadesIds: ['prp_005'],
    totalCobradoMes: 850000,
    totalRecibirMes: 794750,
  },
  {
    id: 'own_005',
    nombre: 'Martín',
    apellido: 'Bravo',
    cuit: '20-56789012-6',
    email: 'martinbravo@gmail.com',
    telefono: '+54 11 2345 1357',
    cbuAlias: 'bravo.martin.cap',
    comisionPct: 8,
    notas: 'Inmueble en USD — el inquilino paga en pesos al MEP.',
    createdAt: '2026-03-01',
    propiedadesIds: ['prp_006'],
    totalCobradoMes: 0,
    totalRecibirMes: 0,
  },
];

// Propiedades: una por cada contrato actual (cnt_001..cnt_006). El detalle
// de la propiedad es la vista principal del panel — desde acá se accede a
// inquilino, propietarios, contrato y reclamos relacionados.
export const propiedadesMock: Propiedad[] = [
  {
    id: 'prp_001',
    direccion: 'Gorriti 4521, 3°B',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'DEPARTAMENTO',
    ambientes: 2,
    m2: 48,
    fotoUrl: null,
    estado: 'ALQUILADA',
    propietariosIds: ['own_001'],
    contratoActualId: 'cnt_001',
    createdAt: '2024-08-15',
  },
  {
    id: 'prp_002',
    direccion: 'Av. Cabildo 2890, 7°A',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'DEPARTAMENTO',
    ambientes: 3,
    m2: 72,
    fotoUrl: null,
    estado: 'ALQUILADA',
    propietariosIds: ['own_002'],
    contratoActualId: 'cnt_002',
    createdAt: '2023-11-02',
  },
  {
    id: 'prp_003',
    direccion: 'Jorge Newbery 1820',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'CASA',
    ambientes: 4,
    m2: 110,
    fotoUrl: null,
    estado: 'ALQUILADA',
    propietariosIds: ['own_003'],
    contratoActualId: 'cnt_003',
    createdAt: '2025-02-20',
  },
  {
    id: 'prp_004',
    direccion: 'Honduras 4490, PB',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'LOCAL',
    ambientes: null,
    m2: 95,
    fotoUrl: null,
    estado: 'ALQUILADA',
    propietariosIds: ['own_002'],
    contratoActualId: 'cnt_004',
    createdAt: '2024-11-01',
  },
  {
    id: 'prp_005',
    direccion: 'Salguero 2240, 12°D',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'DEPARTAMENTO',
    ambientes: 4,
    m2: 95,
    fotoUrl: null,
    estado: 'ALQUILADA',
    propietariosIds: ['own_004'],
    contratoActualId: 'cnt_005',
    createdAt: '2022-05-10',
  },
  {
    id: 'prp_006',
    direccion: 'Olleros 3920',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    tipo: 'DEPARTAMENTO',
    ambientes: 3,
    m2: 80,
    fotoUrl: null,
    estado: 'EN_EDICION',
    propietariosIds: ['own_005'],
    contratoActualId: 'cnt_006', // borrador
    createdAt: '2026-03-01',
  },
];

export const eventosMock = [
  { id: 'e1', tipo: 'pago', titulo: 'Cobraste a Juan Pérez', subtitulo: 'Hace 12 minutos · $620.000', icono: 'dollar' },
  { id: 'e2', tipo: 'reclamo', titulo: 'Nuevo reclamo de Mariela Sosa', subtitulo: 'Hace 2 hs · Plomería · Media', icono: 'wrench' },
  { id: 'e3', tipo: 'aumento', titulo: 'Ajuste aplicado a 5 contratos', subtitulo: 'Hace 1 día · ICL +18,4%', icono: 'trending-up' },
  { id: 'e4', tipo: 'screening', titulo: 'Screening de Tomás Bravo', subtitulo: 'Hace 1 día · APTO', icono: 'shield-check' },
] as const;
