-- T-23-N4 · Baja lógica del propietario.
--
-- Hasta ahora `requirePropietario` sólo comprobaba que la fila (id, inmobiliariaId)
-- existiera: no había NADA que mirar para cortarle el acceso a alguien. La única
-- forma de revocarle la sesión a un propietario era BORRAR su fila — que tiene
-- rendiciones, participaciones y contratos colgando, o sea que en la práctica no
-- se podía. Y su token del portal dura 7 días, sin logout server-side ni denylist.
--
-- El portal expone plata de terceros: nombre del inquilino, su morosidad de los
-- últimos 6 períodos, el desglose de la rendición y los reclamos con el texto que
-- escribió el inquilino. Que eso no tenga forma de cortarse es el agujero.
--
-- Misma convención que `Sociedad.activa` ("baja lógica") y `Usuario.activo`.
--
-- DEFAULT true + NOT NULL: las filas existentes quedan activas, así que aplicar
-- esto no le saca el acceso a nadie.
--
-- ORDEN: el código nuevo lee `activo` en el guard del portal, así que esta columna
-- tiene que existir antes de que el proceso levante. Y así es: el arranque de la
-- API es `pnpm db:deploy && exec node dist/index.js` (apps/api/Dockerfile:30), o
-- sea que `prisma migrate deploy` corre PRIMERO y, si falla, el `&&` impide que el
-- contenedor arranque. No hay ningún paso manual que hacer.
--
-- (Una versión anterior de este comentario decía que las migraciones se aplican a
-- mano "porque no hay railway.json ni Procfile". Era falso: la búsqueda no incluyó
-- el Dockerfile, que es donde estaba. Se corrige acá porque el consejo equivocado
-- invitaba a tocar la base de producción sin ninguna necesidad.)
--
-- Lo que sí se eligió a propósito: que el guard falle ruidosamente si la columna no
-- estuviera, en vez de degradar en silencio. Un guard que se saltea el chequeo
-- porque le falta un campo es peor que uno que se cae.

ALTER TABLE "propietarios"
  ADD COLUMN IF NOT EXISTS "activo" BOOLEAN NOT NULL DEFAULT true;
